services:
  - type: web
    name: data-analytics-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1